/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CIntegrationJ */

#ifndef _Included_CIntegrationJ
#define _Included_CIntegrationJ
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CIntegrationJ
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_CIntegrationJ_add
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
